"""empty message

Revision ID: a20f01f09d82
Revises: 3707c67de428
Create Date: 2025-11-25 09:43:06.926454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20f01f09d82'
down_revision = '3707c67de428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FOOD', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FOOD', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
