"""add pref_code and pref_name to events

Revision ID: 36ea9c5ffb5c
Revises: fe64772fa017
Create Date: 2026-01-21 10:44:51.766775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ea9c5ffb5c'
down_revision = 'fe64772fa017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pref_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('pref_name')
        batch_op.drop_column('pref_code')

    # ### end Alembic commands ###
