"""initial schema

Revision ID: 5802ec72df8a
Revises: 
Create Date: 2026-01-23 10:14:43.181068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5802ec72df8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('event_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('pref_code', sa.String(length=10), nullable=True),
    sa.Column('pref_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('event_code')
    )
    op.create_table('spots',
    sa.Column('spot_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('pref_code', sa.Integer(), nullable=True),
    sa.Column('pref_name_ja', sa.String(length=50), nullable=True),
    sa.Column('pref_name_en', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('spot_id')
    )
    op.create_table('BOOKMARK',
    sa.Column('bookmark_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('thumb', sa.String(length=255), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('bookmark_id')
    )
    op.create_table('STAY',
    sa.Column('stay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=100), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('stay_id')
    )
    op.create_table('TRAVEL_RECORD',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prefecture', sa.String(length=20), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FOOD',
    sa.Column('food_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('food_name', sa.String(length=100), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('evaluation', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stay_id'], ['STAY.stay_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('PHOTO',
    sa.Column('photo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['FOOD.food_id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.spot_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['STAY.stay_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PHOTO')
    op.drop_table('FOOD')
    op.drop_table('TRAVEL_RECORD')
    op.drop_table('STAY')
    op.drop_table('BOOKMARK')
    op.drop_table('spots')
    op.drop_table('events')
    op.drop_table('USER')
    # ### end Alembic commands ###
