"""remove date to events

Revision ID: 65f8507e46e9
Revises: 36ea9c5ffb5c
Create Date: 2026-01-21 14:08:54.077583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f8507e46e9'
down_revision = '36ea9c5ffb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('area')
        batch_op.drop_column('image')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('area', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
