"""initial schema

Revision ID: 97b0a595e356
Revises: 6476f1bd4b4a
Create Date: 2025-12-04 11:41:25.179326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b0a595e356'
down_revision = '6476f1bd4b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SPOT', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SPOT', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
