"""add month to events

Revision ID: eb87a4ff7a79
Revises: e92dd8068399
Create Date: 2026-01-21 10:40:34.462450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb87a4ff7a79'
down_revision = 'e92dd8068399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('month')

    # ### end Alembic commands ###
